### PR TITLE
docs: 构建说明. #37

### PR DESCRIPTION
**Pull request by mossxzzom**

### CODE REVIEW

**Review by zBo1997 — APPROVED** [review]
approve

**Review by zBo1997 — APPROVED** [review]
approve

**Review by zBo1997 — APPROVED** [review]
approve

**Review by zBo1997 — APPROVED** [review]
approve

**Review by zBo1997 — CHANGES_REQUESTED** [review]
approve

**Review by zBo1997 — APPROVED** [review]
approve

**Review by flower1360 — APPROVED** [review]
lgtm

**Review by zBo1997 — CHANGES_REQUESTED** [review]
approve update

**Review by zBo1997 — APPROVED** [review]
approve changes

**Pull request merged**
